---
name: dataset

channels:
  - conda-forge

dependencies:
  - python=3.9.6
  - ipykernel
  - pip
  - pip:
    - numpy==1.21.2
    - pandas==1.3.3
    - jupyterlab==3.1.14
    - scikit-learn==1.0
    - matplotlib==3.4.3